### ISSUE TITLE
Nothing works except for syntax highlighting 

### ISSUE THREAD

**Issue by RHL120** [ShinKage/idris2-nvim#26]
Hello, I have been trying to setup this plugin for my neovim.
I have installed idris2 and idris2-pack using this `bash -c "$(curl -fsSL https://raw.githubusercontent.com/stefan-hoeck/idris2-pack/main/install.bash)"` shown on their [github page](https://github.com/stefan-hoeck/idris2-pack#quick-installation). Then I proceed to install idris2-lsp by using their [recommended method (pack)](https://github.com/idris-community/idris2-lsp#installation-with-pack-recommended). I added this plugin with packer for neovim and I inserted `require('idris2').setup({})` into my config file. When I edit any idris file (a file that ends with .idr). I get syntax highlighting but no autocomplete, no error reporting and no interactive development. I am sorry if this is an invalid issue but I have exhausted all solutions I could think of.
Thanks for your time!
PS: here is my nvim config: https://github.com/RHL120/neovimcfg. The only files that matter are probably:
 - [after/plugin/idris.lua](https://github.com/RHL120/neovimcfg/blob/master/after/plugin/idris.lua)
 - [lua/plugins.lua](https://github.com/RHL120/neovimcfg/blob/master/lua/plugins.lua)
 - [after/plugin/lsp.lua](https://github.com/RHL120/neovimcfg/blob/master/lua/plugins.lua)

**Comment by ShinKage** [comment]
Is there an ipkg file in the directory of the .idr file or uproot? The LSP server requires an ipkg file to function correctly as stated [here](https://github.com/idris-community/idris2-lsp#readme).

**Comment by RHL120** [comment]
> Is there an ipkg file in the directory of the .idr file or uproot? The LSP server requires an ipkg file to function correctly as stated [here](https://github.com/idris-community/idris2-lsp#readme).

Oops. I am really sorry for wasting your time. This works, thank you very much.

**Comment by RHL120** [comment]
> > Oops. I am really sorry for wasting your time. This works, thank you very much.
> 
> Don't worry, I really should find a way to notify the user about the issue within neovim.

I don't know how they do it but rust analyzer have it:
```
[lspconfig] cmd ("cargo metadata --no-deps --format-version 1") failed:
error: could not find `Cargo.toml` in `/home/rhl120` or any parent directory
```

**Comment by ShinKage** [comment]
Added a warning message.
